{{- if .Values.metrics.podMonitor.enabled -}}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "go-echo-starter.fullname" . }}
  {{- with .Values.metrics.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "go-echo-starter.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "go-echo-starter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: {{ .Values.metrics.podMonitor.port }}
      path: {{ .Values.metrics.podMonitor.path }}
      scheme: {{ .Values.metrics.podMonitor.scheme }}
      interval: {{ .Values.metrics.podMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
