package application

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"log/slog"
	"math/big"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/joomcode/errorx"
	"github.com/labstack/echo/v5"
	mw "github.com/labstack/echo/v5/middleware"
	"golang.org/x/crypto/acme/autocert"
	"golang.org/x/net/netutil"

	ce "github.com/servercurio/go-echo-starter/internal/errors"
	"github.com/servercurio/go-echo-starter/internal/logging"
)

// InMemoryCertificate holds a PEM-encoded ECDSA keypair and certificate
// generated by the ephemeral TLS path (autoTlsEnabled && !UseAcmeIssuer).
// Kept on the Application across the boot phases so configureTlsServer can
// generate it once and startTlsServer can serve it without re-generation.
type InMemoryCertificate struct {
	PrivateKey  []byte
	PublicKey   []byte
	Certificate []byte
}

// tlsEnabled reports whether the TLS listener should be brought up at all.
// True when Https.Enabled and either a static cert/key pair is configured
// or auto-issuance applies.
func (app *Application) tlsEnabled() bool {
	return (app.config.Server.Https.Enabled && app.config.Server.Https.Certificate != "" &&
		app.config.Server.Https.Key != "") || app.autoTlsEnabled()
}

// autoTlsEnabled reports whether the daemon should issue its own
// certificate (either via ACME or the ephemeral self-signed path). True
// when TLS is enabled but at least one of cert/key is missing.
func (app *Application) autoTlsEnabled() bool {
	return app.config.Server.Https.Enabled &&
		(app.config.Server.Https.Certificate == "" || app.config.Server.Https.Key == "")
}

// configureTlsServer wires middleware, CORS, body-size limit, and
// certificate sourcing onto app.tlsServer. The certificate path branches
// three ways: static cert/key (no extra setup), ACME via autocert (cache
// dir and host policy configured here), and ephemeral self-signed
// (generated synchronously here and stored on the Application).
func (app *Application) configureTlsServer() error {
	if app.config.Server.Https == nil || !app.config.Server.Https.Enabled {
		return nil
	}

	app.tlsServer.Use(app.middleware...)

	if cors := CorsMiddleware(app.config.Server.Cors); cors != nil {
		app.tlsServer.Use(cors)
	}

	bodyLimit, err := parseByteSize(app.config.Server.Https.MaxBodySize)
	if err != nil {
		return errorx.IllegalArgument.Wrap(err, "invalid https max body size %q", app.config.Server.Https.MaxBodySize)
	}
	app.tlsServer.Use(mw.BodyLimit(bodyLimit))

	app.tlsServer.Logger = slog.New(slog.DiscardHandler)

	autoTlsEnabled := app.autoTlsEnabled()

	if autoTlsEnabled {
		if app.config.Server.Https.UseAcmeIssuer {
			logging.Daemon.Debug().
				Msg("auto tls - configuring automatic tls support with an ACME issuer")

			if err := app.configureAutoTlsManager(); err != nil {
				logging.Daemon.Error().
					Err(err).
					Msg("auto tls - failed to configure automatic tls support")
				return err
			}
		} else {
			logging.Daemon.Debug().
				Str("algorithm", "ECDSA").
				Str("curve", "P384").
				Msg("ephemeral tls - generating self-signed certificate")
			var err error
			if app.certificate, err = app.generateTlsCertificate(); err != nil {
				return err
			}
			logging.Daemon.Info().
				Msg("ephemeral tls - self-signed certificate generated")
		}
	}

	return nil
}

// generateTlsCertificate produces a fresh ECDSA-P384 self-signed
// certificate for the ephemeral TLS path. The certificate is valid for one
// year and includes Hostname (or "localhost") plus a www. and 127.0.0.1
// SAN where appropriate. Returns the PEM-encoded private key, public key,
// and certificate together so startTlsServer can serve them without
// re-deriving anything.
func (app *Application) generateTlsCertificate() (imc *InMemoryCertificate, err error) {
	imc = &InMemoryCertificate{}
	var pk *ecdsa.PrivateKey

	if pk, err = ecdsa.GenerateKey(elliptic.P384(), rand.Reader); err != nil {
		wErr := errorx.ExternalError.Wrap(err, "failed to generate ephemeral ECDSA private key")
		logging.Daemon.Error().
			Err(wErr).
			Msg("ephemeral tls - failed to generate ECDSA private key")
		return nil, wErr
	}

	// 128-bit random serial per RFC 5280 §4.1.2.2; avoids reusing the same
	// serial across daemon restarts, which would alias entries in client
	// certificate caches.
	serialMax := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialMax)
	if err != nil {
		wErr := errorx.ExternalError.Wrap(err, "failed to generate certificate serial number")
		logging.Daemon.Error().
			Err(wErr).
			Msg("ephemeral tls - failed to generate certificate serial number")
		return nil, wErr
	}

	cn := "localhost"
	if app.config.Server.Https.Hostname != "" {
		cn = app.config.Server.Https.Hostname
	}

	var altNames []string

	if app.config.Server.Https.Hostname != "" {
		if !strings.HasPrefix(app.config.Server.Https.Hostname, "www") {
			altNames = append(altNames, "www."+app.config.Server.Https.Hostname)
		}

		if app.config.Server.Https.Hostname == "localhost" {
			altNames = append(altNames, "127.0.0.1")
		}
	} else {
		altNames = append(altNames, "127.0.0.1")
	}

	template := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: cn},
		NotBefore:    time.Now().UTC().Add(-24 * time.Hour),
		NotAfter:     time.Now().UTC().Add(365 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IsCA:         false,
		DNSNames:     altNames,
	}

	var certDerBytes []byte
	if certDerBytes, err = x509.CreateCertificate(rand.Reader, template, template, pk.Public(), pk); err != nil {
		wErr := errorx.ExternalError.Wrap(err, "failed to create certificate")
		logging.Daemon.Error().
			Err(wErr).
			Msg("ephemeral tls - failed to create certificate")
		return nil, wErr
	}

	imc.Certificate = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDerBytes})

	var pkDerBytes []byte
	if pkDerBytes, err = x509.MarshalPKCS8PrivateKey(pk); err != nil {
		wErr := errorx.ExternalError.Wrap(err, "failed to marshal private key")
		logging.Daemon.Error().
			Err(wErr).
			Msg("ephemeral tls - failed to marshal private key")
		return nil, wErr
	}

	imc.PrivateKey = pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: pkDerBytes})

	var pubDerBytes []byte
	if pubDerBytes, err = x509.MarshalPKIXPublicKey(pk.Public()); err != nil {
		wErr := errorx.ExternalError.Wrap(err, "failed to marshal public key")
		logging.Daemon.Error().
			Err(wErr).
			Msg("ephemeral tls - failed to marshal public key")
		return nil, wErr
	}

	imc.PublicKey = pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDerBytes})

	return
}

// configureAutoTlsManager prepares the autocert cache directory used by the
// ACME path. Falls back to <home>/.cache/<name>/certificates when the
// operator hasn't pinned a path; falls back further to /etc/<name>/certificates
// when there's no usable home directory. Tightens the directory to 0700
// even on a pre-existing path because the cache holds private keys.
func (app *Application) configureAutoTlsManager() error {
	cacheDir := strings.TrimSpace(app.config.Server.Https.CertificateCache)

	if cacheDir == "" {
		if app.userHomeDirectory != "" && app.userHomeDirectory != "." {
			cacheDir = filepath.Join(app.userHomeDirectory, ".cache", app.Name, "certificates")
		} else {
			cacheDir = filepath.Join(string(filepath.Separator), "etc", app.Name, "certificates")
		}
	}

	if err := os.MkdirAll(cacheDir, 0700); err != nil { //nolint:gosec // 0700 is required: directories need execute bit to traverse, and the cache holds private keys we want owner-only
		var wErr error
		switch {
		case os.IsPermission(err):
			wErr = ce.FileAccessDenied.Wrap(err, "permission denied: %s", cacheDir)
		case os.IsExist(err):
			wErr = ce.InvalidFilePath.Wrap(err, "file already exists and is a regular file: %s", cacheDir)
		default:
			wErr = errorx.ExternalError.Wrap(err, "failed to create directory: %s", cacheDir)
		}

		logging.Daemon.Error().
			Err(wErr).
			Str("path", cacheDir).
			Msg("auto tls - failed to create certificate cache directory")
		return wErr
	}

	// MkdirAll honours the mode only when creating; if cacheDir already
	// existed with looser permissions (e.g. from a pre-fix daemon version),
	// tighten it now. The cache holds private keys and ACME account state.
	if err := os.Chmod(cacheDir, 0700); err != nil { //nolint:gosec // 0700 is required: directories need execute bit to traverse, and the cache holds private keys we want owner-only
		logging.Daemon.Warn().
			Err(err).
			Str("path", cacheDir).
			Msg("auto tls - could not tighten certificate cache directory permissions")
	}

	app.tlsServer.Logger = nil

	logging.Daemon.Info().
		Str("certificateCache", cacheDir).
		Msg("auto tls - automatic tls support configured")

	return nil
}

// hardenedTLSConfig returns the *tls.Config used for the static-cert and
// self-signed paths. The ACME path uses autocert.Manager.TLSConfig() which
// already produces a hardened config.
//
// CipherSuites only configures TLS 1.2 — Go selects TLS 1.3 ciphers
// automatically and ignores this slice for 1.3 connections. The set below
// mirrors Mozilla "intermediate" minus AES-CBC (Go drops CBC suites in
// modern releases regardless).
func hardenedTLSConfig() *tls.Config {
	return &tls.Config{
		MinVersion: tls.VersionTLS12,
		NextProtos: []string{"h2", "http/1.1"},
		CurvePreferences: []tls.CurveID{
			tls.X25519,
			tls.CurveP256,
		},
		CipherSuites: []uint16{
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
		},
	}
}

// startTlsServer launches the TLS listener and blocks until ctx cancels
// (or the server returns an unexpected error). Branches across the three
// certificate-source paths (ACME, ephemeral self-signed, static cert/key)
// and across the two listener-cap states (with / without
// netutil.LimitListener). When the cap is active the TLS handshake is
// performed by tls.NewListener around the limited listener so the cap
// applies before the handshake (cheap rejection of slowloris).
func (app *Application) startTlsServer(ctx context.Context) {
	if !app.config.Server.Https.Enabled {
		return
	}

	cacheDir := strings.TrimSpace(app.config.Server.Https.CertificateCache)
	address := fmt.Sprintf("%s:%d", app.config.Server.Https.BindAddress, app.config.Server.Https.Port)

	logging.Daemon.Info().
		Str("address", address).
		Bool("autoCertIssuance", app.autoTlsEnabled()).
		Bool("ephemeralCertIssuance", !app.config.Server.Https.UseAcmeIssuer).
		Msg("https server started")

	tlsCfg := app.config.Server.Https
	sc := &echo.StartConfig{
		HideBanner:      true,
		Address:         address,
		GracefulTimeout: tlsCfg.ShutdownTimeout,
		// Static-cert and self-signed paths use this TLSConfig; ACME path
		// overrides it below with autocert.Manager.TLSConfig() (which also
		// pins MinVersion to TLS 1.2 and a hardened cipher set internally).
		TLSConfig: hardenedTLSConfig(),
		BeforeServeFunc: func(s *http.Server) error {
			s.ReadTimeout = tlsCfg.ReadTimeout
			s.ReadHeaderTimeout = tlsCfg.ReadHeaderTimeout
			s.WriteTimeout = tlsCfg.WriteTimeout
			s.IdleTimeout = tlsCfg.IdleTimeout
			return nil
		},
	}

	if app.autoTlsEnabled() {
		if app.config.Server.Https.UseAcmeIssuer {
			hp := autocert.HostWhitelist("localhost")
			if app.config.Server.Https.Hostname != "" {
				hp = autocert.HostWhitelist(app.config.Server.Https.Hostname)
			}

			acm := &autocert.Manager{
				Prompt:     autocert.AcceptTOS,
				Cache:      autocert.DirCache(cacheDir),
				HostPolicy: hp,
			}

			// autocert.TLSConfig() returns a config with GetCertificate set
			// and MinVersion: TLS 1.2 already; replacing our explicit config
			// with it is safe.
			sc.TLSConfig = acm.TLSConfig()

			if err := app.applyListenerLimit(ctx, sc, address, true); err != nil {
				return
			}
			if err := sc.Start(ctx, app.tlsServer); err != nil && !errors.Is(err, http.ErrServerClosed) {
				logging.Daemon.Error().
					Err(errorx.EnsureStackTrace(err)).
					Msg("https server shutting down due to an error")
			}
			return
		}

		// Self-signed ephemeral path. StartTLS sets sc.TLSConfig.Certificates
		// and then calls sc.start, which only wraps the listener with TLS
		// when sc.Listener is nil — so when we inject a LimitListener we
		// also have to take over TLS-config setup here.
		if app.maxListenerConnections() > 0 {
			cer, err := tls.X509KeyPair(app.certificate.Certificate, app.certificate.PrivateKey)
			if err != nil {
				logging.Daemon.Error().Err(err).Msg("https server failed to load ephemeral key pair")
				return
			}
			sc.TLSConfig.Certificates = []tls.Certificate{cer}
			if err := app.applyListenerLimit(ctx, sc, address, true); err != nil {
				return
			}
			if err := sc.Start(ctx, app.tlsServer); err != nil && !errors.Is(err, http.ErrServerClosed) {
				logging.Daemon.Error().
					Err(errorx.EnsureStackTrace(err)).
					Msg("https server shutting down due to an error")
			}
			return
		}

		if err := sc.StartTLS(ctx, app.tlsServer, app.certificate.Certificate, app.certificate.PrivateKey); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logging.Daemon.Error().
				Err(errorx.EnsureStackTrace(err)).
				Msg("https server shutting down due to an error")
		}
		return
	}

	// Static cert/key path. Same caveat as the ephemeral branch above: when
	// we inject a LimitListener we also assume TLS-config ownership.
	if app.maxListenerConnections() > 0 {
		cer, err := loadStaticKeyPair(app.config.Server.Https.Certificate, app.config.Server.Https.Key)
		if err != nil {
			logging.Daemon.Error().Err(err).Msg("https server failed to load static key pair")
			return
		}
		sc.TLSConfig.Certificates = []tls.Certificate{cer}
		if err := app.applyListenerLimit(ctx, sc, address, true); err != nil {
			return
		}
		if err := sc.Start(ctx, app.tlsServer); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logging.Daemon.Error().
				Err(errorx.EnsureStackTrace(err)).
				Msg("https server shutting down due to an error")
		}
		return
	}

	if err := sc.StartTLS(ctx, app.tlsServer, app.config.Server.Https.Certificate, app.config.Server.Https.Key); err != nil && !errors.Is(err, http.ErrServerClosed) {
		logging.Daemon.Error().
			Err(errorx.EnsureStackTrace(err)).
			Msg("https server shutting down due to an error")
	}
}

// applyListenerLimit pre-creates the TCP listener for sc, wraps it with
// netutil.LimitListener (and tls.NewListener when wrapTLS is true), and
// stores the result on sc.Listener so Echo's start() uses our wrapped
// listener verbatim. Returns the listen error (already logged) so the
// caller can return early without serving.
func (app *Application) applyListenerLimit(ctx context.Context, sc *echo.StartConfig, address string, wrapTLS bool) error {
	maxConns := app.maxListenerConnections()
	if maxConns <= 0 {
		return nil
	}
	ln, err := (&net.ListenConfig{}).Listen(ctx, "tcp", address)
	if err != nil {
		logging.Daemon.Error().Err(err).Str("address", address).Msg("server failed to listen")
		return err
	}
	ln = netutil.LimitListener(ln, maxConns)
	if wrapTLS {
		ln = tls.NewListener(ln, sc.TLSConfig)
	}
	sc.Listener = ln
	return nil
}

// loadStaticKeyPair mirrors echo.StartConfig.StartTLS's filepathOrContent
// handling: a string is a filesystem path, a []byte is the raw PEM. The
// LimitListener path bypasses StartTLS and so has to do the same dance
// itself.
func loadStaticKeyPair(cert, key any) (tls.Certificate, error) {
	certBytes, err := pemBytes(cert)
	if err != nil {
		return tls.Certificate{}, err
	}
	keyBytes, err := pemBytes(key)
	if err != nil {
		return tls.Certificate{}, err
	}
	return tls.X509KeyPair(certBytes, keyBytes)
}

// pemBytes returns the PEM bytes for v. Accepts either a []byte (already
// PEM) or a string (filesystem path to read). Mirrors the heuristic Echo's
// StartConfig.StartTLS uses internally.
func pemBytes(v any) ([]byte, error) {
	switch x := v.(type) {
	case []byte:
		return x, nil
	case string:
		return os.ReadFile(x) //nolint:gosec // G304 false positive: x is the operator-supplied APP_SERVER_HTTPS_CERTIFICATE path, not user input
	default:
		return nil, errors.New("unexpected cert/key type (want string path or []byte PEM)")
	}
}
